# Обработка заказа интернет-магазина
pool_main, lanes_main = DIAGRAM.add_pool(ROOT_PROCESS_ID, ['Покупатель', 'Менеджер', 'Склад', 'Бухгалтерия', 'Служба доставки'], 'Интернет-магазин')
pool_bank = DIAGRAM.add_black_box_pool('Платёжный шлюз банка')
order = DIAGRAM.add_user_task('Оформить заказ', lanes_main[0])
gw_pay = DIAGRAM.add_exclusive_gateway('Способ оплаты?', lanes_main[0])
pay = DIAGRAM.add_user_task('Оплатить заказ онлайн', lanes_main[0])
gw_pay_join = DIAGRAM.add_exclusive_gateway('', lanes_main[1])
confirm = DIAGRAM.add_user_task('Подтвердить заказ', lanes_main[1])
p_split = DIAGRAM.add_parallel_gateway('', lanes_main[1])
pick = DIAGRAM.add_manual_task('Собрать заказ', lanes_main[2])
docs = DIAGRAM.add_service_task('Сформировать чек и документы', lanes_main[3])
p_join = DIAGRAM.add_parallel_gateway('', lanes_main[4])
deliver = DIAGRAM.add_manual_task('Доставить заказ', lanes_main[4])
receive = DIAGRAM.add_task('Получить заказ', lanes_main[0])
gw_accept = DIAGRAM.add_exclusive_gateway('Покупатель принял заказ?', lanes_main[0])
return_goods = DIAGRAM.add_manual_task('Вернуть товар на склад', lanes_main[4])
process_return = DIAGRAM.add_task('Оформить возврат', lanes_main[2])
end_return = DIAGRAM.add_end_event('Заказ возвращён', lanes_main[2], None)
DIAGRAM.add_link(ROOT_START_TASK_ID, order)
DIAGRAM.add_link(order, gw_pay)
DIAGRAM.add_link(gw_pay, pay, 'Картой онлайн')
DIAGRAM.add_link(gw_pay, gw_pay_join, 'При получении')
DIAGRAM.add_link(pay, gw_pay_join)
DIAGRAM.add_link(gw_pay_join, confirm)
DIAGRAM.add_link(confirm, p_split)
DIAGRAM.add_link(p_split, pick)
DIAGRAM.add_link(p_split, docs)
DIAGRAM.add_link(pick, p_join)
DIAGRAM.add_link(docs, p_join)
DIAGRAM.add_link(p_join, deliver)
DIAGRAM.add_link(deliver, receive)
DIAGRAM.add_link(receive, gw_accept)
DIAGRAM.add_link(gw_accept, ROOT_END_TASK_ID, 'Да')
DIAGRAM.add_link(gw_accept, return_goods, 'Нет')
DIAGRAM.add_link(return_goods, process_return)
DIAGRAM.add_link(process_return, end_return)
DIAGRAM.add_message_link(pay, pool_bank, 'Платёж')
DIAGRAM.add_message_link(pool_bank, confirm, 'Подтверждение оплаты')
