# Обработка заказа интернет-магазина
pool_main, lanes_main = DIAGRAM.add_pool(ROOT_PROCESS_ID, ['Покупатель', 'Менеджер', 'Склад', 'Бухгалтерия', 'Служба доставки'], 'Интернет-магазин')
pool_external_0 = DIAGRAM.add_black_box_pool('Платёжный шлюз банка')
node_0 = DIAGRAM.add_user_task('Оформить заказ', lanes_main[0], id='order')
node_1 = DIAGRAM.add_exclusive_gateway('Способ оплаты?', lanes_main[0], id='gw_pay')
node_2 = DIAGRAM.add_user_task('Оплатить заказ онлайн', lanes_main[0], id='pay')
node_3 = DIAGRAM.add_exclusive_gateway('', lanes_main[1], id='gw_pay_join')
node_4 = DIAGRAM.add_user_task('Подтвердить заказ', lanes_main[1], id='confirm')
node_5 = DIAGRAM.add_parallel_gateway('', lanes_main[1], id='p_split')
node_6 = DIAGRAM.add_manual_task('Собрать заказ', lanes_main[2], id='pick')
node_7 = DIAGRAM.add_service_task('Сформировать чек и документы', lanes_main[3], id='docs')
node_8 = DIAGRAM.add_parallel_gateway('', lanes_main[4], id='p_join')
node_9 = DIAGRAM.add_manual_task('Доставить заказ', lanes_main[4], id='deliver')
node_10 = DIAGRAM.add_task('Получить заказ', lanes_main[0], id='receive')
node_11 = DIAGRAM.add_exclusive_gateway('Покупатель принял заказ?', lanes_main[0], id='gw_accept')
node_12 = DIAGRAM.add_manual_task('Вернуть товар на склад', lanes_main[4], id='return_goods')
node_13 = DIAGRAM.add_task('Оформить возврат', lanes_main[2], id='process_return')
node_14 = DIAGRAM.add_end_event('Заказ возвращён', lanes_main[2], None, id='end_return')
DIAGRAM.add_link(ROOT_START_TASK_ID, node_0)
DIAGRAM.add_link(node_0, node_1)
DIAGRAM.add_link(node_1, node_2, 'Картой онлайн')
DIAGRAM.add_link(node_1, node_3, 'При получении')
DIAGRAM.add_link(node_2, node_3)
DIAGRAM.add_link(node_3, node_4)
DIAGRAM.add_link(node_4, node_5)
DIAGRAM.add_link(node_5, node_6)
DIAGRAM.add_link(node_5, node_7)
DIAGRAM.add_link(node_6, node_8)
DIAGRAM.add_link(node_7, node_8)
DIAGRAM.add_link(node_8, node_9)
DIAGRAM.add_link(node_9, node_10)
DIAGRAM.add_link(node_10, node_11)
DIAGRAM.add_link(node_11, ROOT_END_TASK_ID, 'Да')
DIAGRAM.add_link(node_11, node_12, 'Нет', default=True)
DIAGRAM.add_link(node_12, node_13)
DIAGRAM.add_link(node_13, node_14)
DIAGRAM.add_message_link(node_2, pool_external_0, 'Платёж')
DIAGRAM.add_message_link(pool_external_0, node_4, 'Подтверждение оплаты')
