# Подбор сотрудника
pool_main, lanes_main = DIAGRAM.add_pool(ROOT_PROCESS_ID, ['Руководитель подразделения', 'HR-менеджер', 'Кандидат', 'Служба безопасности', 'Директор'], 'Компания')
node_0 = DIAGRAM.add_user_task('Создать заявку на подбор', lanes_main[0], id='request')
node_1 = DIAGRAM.add_user_task('Опубликовать вакансию', lanes_main[1], id='publish')
node_2 = DIAGRAM.add_user_task('Отобрать резюме', lanes_main[1], id='screen')
node_3 = DIAGRAM.add_task('Провести первичное интервью', lanes_main[1], id='interview')
node_4 = DIAGRAM.add_exclusive_gateway('Кандидат подходит?', lanes_main[1], id='gw_fit')
node_5 = DIAGRAM.add_send_task('Отправить отказ кандидату', lanes_main[1], id='reject')
node_6 = DIAGRAM.add_task('Выполнить тестовое задание', lanes_main[2], id='test')
node_7 = DIAGRAM.add_task('Провести техническое интервью', lanes_main[0], id='tech')
node_8 = DIAGRAM.add_user_task('Принять решение по кандидату', lanes_main[0], id='decide')
node_9 = DIAGRAM.add_inclusive_gateway('Нужные проверки?', lanes_main[0], id='gw_checks')
node_10 = DIAGRAM.add_task('Проверить кандидата', lanes_main[3], id='sb')
node_11 = DIAGRAM.add_user_task('Согласовать кандидата', lanes_main[4], id='approve')
node_12 = DIAGRAM.add_inclusive_gateway('', lanes_main[1], id='gw_checks_join')
node_13 = DIAGRAM.add_send_task('Направить оффер', lanes_main[1], id='offer')
node_14 = DIAGRAM.add_exclusive_gateway('Оффер принят?', lanes_main[2], id='gw_offer')
node_15 = DIAGRAM.add_user_task('Оформить на работу', lanes_main[1], id='hire')
node_16 = DIAGRAM.add_end_event('Кандидат отказался', lanes_main[2], None, id='end_no')
DIAGRAM.add_link(ROOT_START_TASK_ID, node_0)
DIAGRAM.add_link(node_0, node_1)
DIAGRAM.add_link(node_1, node_2)
DIAGRAM.add_link(node_2, node_3)
DIAGRAM.add_link(node_3, node_4)
DIAGRAM.add_link(node_4, node_6, 'Да')
DIAGRAM.add_link(node_4, node_5, 'Нет', default=True)
DIAGRAM.add_link(node_5, node_2)
DIAGRAM.add_link(node_6, node_7)
DIAGRAM.add_link(node_7, node_8)
DIAGRAM.add_link(node_8, node_9)
DIAGRAM.add_link(node_9, node_10, 'Нужна проверка СБ')
DIAGRAM.add_link(node_9, node_11, 'Нужно согласование')
DIAGRAM.add_link(node_9, node_12, 'Проверки не нужны', default=True)
DIAGRAM.add_link(node_10, node_12)
DIAGRAM.add_link(node_11, node_12)
DIAGRAM.add_link(node_12, node_13)
DIAGRAM.add_link(node_13, node_14)
DIAGRAM.add_link(node_14, node_15, 'Да')
DIAGRAM.add_link(node_14, node_16, 'Нет', default=True)
DIAGRAM.add_link(node_15, ROOT_END_TASK_ID)
