# Подбор сотрудника
pool_main, lanes_main = DIAGRAM.add_pool(ROOT_PROCESS_ID, ['Руководитель подразделения', 'HR-менеджер', 'Кандидат', 'Служба безопасности', 'Директор'], 'Компания')
request = DIAGRAM.add_user_task('Создать заявку на подбор', lanes_main[0])
publish = DIAGRAM.add_user_task('Опубликовать вакансию', lanes_main[1])
screen = DIAGRAM.add_user_task('Отобрать резюме', lanes_main[1])
interview = DIAGRAM.add_task('Провести первичное интервью', lanes_main[1])
gw_fit = DIAGRAM.add_exclusive_gateway('Кандидат подходит?', lanes_main[1])
reject = DIAGRAM.add_send_task('Отправить отказ кандидату', lanes_main[1])
test = DIAGRAM.add_task('Выполнить тестовое задание', lanes_main[2])
tech = DIAGRAM.add_task('Провести техническое интервью', lanes_main[0])
decide = DIAGRAM.add_user_task('Принять решение по кандидату', lanes_main[0])
gw_checks = DIAGRAM.add_inclusive_gateway('Нужные проверки?', lanes_main[0])
sb = DIAGRAM.add_task('Проверить кандидата', lanes_main[3])
approve = DIAGRAM.add_user_task('Согласовать кандидата', lanes_main[4])
gw_checks_join = DIAGRAM.add_inclusive_gateway('', lanes_main[1])
offer = DIAGRAM.add_send_task('Направить оффер', lanes_main[1])
gw_offer = DIAGRAM.add_exclusive_gateway('Оффер принят?', lanes_main[2])
hire = DIAGRAM.add_user_task('Оформить на работу', lanes_main[1])
end_no = DIAGRAM.add_end_event('Кандидат отказался', lanes_main[2], None)
DIAGRAM.add_link(ROOT_START_TASK_ID, request)
DIAGRAM.add_link(request, publish)
DIAGRAM.add_link(publish, screen)
DIAGRAM.add_link(screen, interview)
DIAGRAM.add_link(interview, gw_fit)
DIAGRAM.add_link(gw_fit, test, 'Да')
DIAGRAM.add_link(gw_fit, reject, 'Нет')
DIAGRAM.add_link(reject, screen)
DIAGRAM.add_link(test, tech)
DIAGRAM.add_link(tech, decide)
DIAGRAM.add_link(decide, gw_checks)
DIAGRAM.add_link(gw_checks, sb, 'Нужна проверка СБ')
DIAGRAM.add_link(gw_checks, approve, 'Нужно согласование')
DIAGRAM.add_link(gw_checks, gw_checks_join, 'Проверки не нужны')
DIAGRAM.add_link(sb, gw_checks_join)
DIAGRAM.add_link(approve, gw_checks_join)
DIAGRAM.add_link(gw_checks_join, offer)
DIAGRAM.add_link(offer, gw_offer)
DIAGRAM.add_link(gw_offer, hire, 'Да')
DIAGRAM.add_link(gw_offer, end_no, 'Нет')
DIAGRAM.add_link(hire, ROOT_END_TASK_ID)
