# Технологическое присоединение к электрическим сетям
pool_main, lanes_main = DIAGRAM.add_pool(ROOT_PROCESS_ID, ['Заявитель', 'Отдел по работе с клиентами', 'Технический отдел', 'Главный инженер', 'Оперативный персонал'], 'Сетевая организация', ids=['applicant', 'clients', 'tech', 'chief', 'ops'])
pool_external_0 = DIAGRAM.add_black_box_pool('Подрядная организация', id='contractor')
node_17 = DIAGRAM.create_subprocess('Построить сетевые объекты', lanes_main[2], id='build')
DIAGRAM.set_details(node_17, 'подрядная организация строит сетевые объекты', '', '', [])
node_0 = DIAGRAM.add_user_task('Подать заявку на присоединение', lanes_main[0], id='apply')
DIAGRAM.set_details(node_0, 'Заявитель подаёт заявку на технологическое присоединение через личный кабинет сетевой организации.', '', '', ['Заявка на технологическое присоединение'])
node_1 = DIAGRAM.add_user_task('Проверить комплектность документов', lanes_main[1], id='check_docs')
DIAGRAM.set_details(node_1, 'Специалист отдела по работе с клиентами проверяет комплектность документов.', '', '', [])
node_2 = DIAGRAM.add_exclusive_gateway('Документы в порядке?', lanes_main[1], id='gw_docs')
DIAGRAM.set_details(node_2, 'Если документов не хватает', '', '', [])
node_3 = DIAGRAM.add_send_task('Уведомить о недостающих документах', lanes_main[1], id='notify_docs')
DIAGRAM.set_details(node_3, 'заявителю направляется уведомление', '', '', [])
node_4 = DIAGRAM.add_user_task('Дополнить документы', lanes_main[0], id='add_docs')
DIAGRAM.set_details(node_4, 'Если документов не хватает, заявителю направляется уведомление, и у него есть 20 рабочих дней на их предоставление; заявитель дополняет документы, и проверка повторяется.', 'В описании не определены точка отсчёта срока и исход при просрочке.', '20 рабочих дней; точку отсчёта необходимо уточнить', ['Недостающие документы'])
node_5 = DIAGRAM.add_task('Проверить свободную мощность', lanes_main[2], id='check_power')
DIAGRAM.set_details(node_5, 'технический отдел проверяет наличие свободной мощности на центре питания', '', '', [])
node_6 = DIAGRAM.add_exclusive_gateway('Мощности достаточно?', lanes_main[2], id='gw_power')
DIAGRAM.set_details(node_6, 'Если мощности недостаточно', '', '', [])
node_7 = DIAGRAM.add_task('Разработать мероприятие по увеличению мощности', lanes_main[2], id='plan_upgrade')
DIAGRAM.set_details(node_7, 'разрабатывается мероприятие по увеличению мощности', '', '', [])
node_8 = DIAGRAM.add_user_task('Согласовать мероприятие', lanes_main[3], id='approve_upgrade')
DIAGRAM.set_details(node_8, 'которое согласует главный инженер', '', '', [])
node_9 = DIAGRAM.add_exclusive_gateway('', lanes_main[2], id='gw_power_join')
node_10 = DIAGRAM.add_parallel_gateway('', lanes_main[2], id='p1')
node_11 = DIAGRAM.add_task('Подготовить технические условия', lanes_main[2], id='tu')
DIAGRAM.set_details(node_11, 'Затем технический отдел готовит технические условия', '', '', ['Технические условия'])
node_12 = DIAGRAM.add_service_task('Рассчитать плату за присоединение', lanes_main[1], id='fee')
DIAGRAM.set_details(node_12, 'отдел по работе с клиентами параллельно рассчитывает плату за присоединение', '', '', [])
node_13 = DIAGRAM.add_parallel_gateway('', lanes_main[1], id='p1_join')
node_14 = DIAGRAM.add_send_task('Направить договор и ТУ', lanes_main[1], id='send_contract')
DIAGRAM.set_details(node_14, 'После этого заявителю направляется договор с техническими условиями.', '', '', ['Договор', 'Технические условия'])
node_15 = DIAGRAM.add_user_task('Подписать договор и оплатить', lanes_main[0], id='sign_pay')
DIAGRAM.set_details(node_15, 'Заявитель подписывает договор и оплачивает услугу.', '', '', ['Договор'])
node_16 = DIAGRAM.add_parallel_gateway('', lanes_main[2], id='p2')
node_21 = DIAGRAM.add_manual_task('Выполнить мероприятия на своей стороне', lanes_main[0], id='own_side')
DIAGRAM.set_details(node_21, 'заявитель выполняет мероприятия на своей стороне', '', '', [])
node_22 = DIAGRAM.add_parallel_gateway('', lanes_main[2], id='p2_join')
node_23 = DIAGRAM.add_manual_task('Провести осмотр электроустановки', lanes_main[2], id='inspect')
DIAGRAM.set_details(node_23, 'После этого инспектор проводит осмотр электроустановки.', 'Инспектор отнесён к техническому отделу — организационную принадлежность нужно подтвердить.', '', [])
node_24 = DIAGRAM.add_exclusive_gateway('Есть замечания?', lanes_main[2], id='gw_remarks')
DIAGRAM.set_details(node_24, 'Если выявлены замечания', '', '', [])
node_25 = DIAGRAM.add_manual_task('Устранить замечания', lanes_main[0], id='fix')
DIAGRAM.set_details(node_25, 'заявитель их устраняет и осмотр повторяется', '', '', [])
node_26 = DIAGRAM.add_manual_task('Подать напряжение', lanes_main[4], id='connect')
DIAGRAM.set_details(node_26, 'оперативный персонал выполняет фактическое присоединение и подача напряжения', '', '', [])
node_27 = DIAGRAM.add_send_task('Оформить и направить акт о присоединении', lanes_main[1], id='act')
DIAGRAM.set_details(node_27, 'отдел по работе с клиентами оформляет акт об осуществлении технологического присоединения и направляет его заявителю', '', '', ['Акт об осуществлении технологического присоединения'])
node_18 = DIAGRAM.add_task('Выполнить проектирование', node_17, id='b1')
DIAGRAM.set_details(node_18, '', 'Детализация строительства из эталонного плана; в исходном описании этот шаг отдельно не указан.', '', [])
node_19 = DIAGRAM.add_task('Выполнить строительно-монтажные работы', node_17, id='b2')
DIAGRAM.set_details(node_19, '', 'Детализация строительства из эталонного плана; в исходном описании этот шаг отдельно не указан.', '', [])
node_20 = DIAGRAM.add_task('Сдать объекты сетевой организации', node_17, id='b3')
DIAGRAM.set_details(node_20, '', 'Детализация строительства из эталонного плана; в исходном описании этот шаг отдельно не указан.', '', [])
DIAGRAM.add_link(ROOT_START_TASK_ID, node_0)
DIAGRAM.add_link(node_0, node_1)
DIAGRAM.add_link(node_1, node_2)
DIAGRAM.add_link(node_2, node_5, 'Да')
DIAGRAM.add_link(node_2, node_3, 'Нет', default=True)
DIAGRAM.add_link(node_3, node_4)
DIAGRAM.add_link(node_4, node_1)
DIAGRAM.add_link(node_5, node_6)
DIAGRAM.add_link(node_6, node_9, 'Да')
DIAGRAM.add_link(node_6, node_7, 'Нет', default=True)
DIAGRAM.add_link(node_7, node_8)
DIAGRAM.add_link(node_8, node_9)
DIAGRAM.add_link(node_9, node_10)
DIAGRAM.add_link(node_10, node_11)
DIAGRAM.add_link(node_10, node_12)
DIAGRAM.add_link(node_11, node_13)
DIAGRAM.add_link(node_12, node_13)
DIAGRAM.add_link(node_13, node_14)
DIAGRAM.add_link(node_14, node_15)
DIAGRAM.add_link(node_15, node_16)
DIAGRAM.add_link(node_16, node_17)
DIAGRAM.add_link(node_16, node_21)
DIAGRAM.add_link(node_17, node_22)
DIAGRAM.add_link(node_21, node_22)
DIAGRAM.add_link(node_22, node_23)
DIAGRAM.add_link(node_23, node_24)
DIAGRAM.add_link(node_24, node_25, 'Да')
DIAGRAM.add_link(node_25, node_23)
DIAGRAM.add_link(node_24, node_26, 'Нет', default=True)
DIAGRAM.add_link(node_26, node_27)
DIAGRAM.add_link(node_27, ROOT_END_TASK_ID)
DIAGRAM.add_link(node_18, node_19)
DIAGRAM.add_link(node_19, node_20)
DIAGRAM.add_message_link(node_17, pool_external_0, 'Заказ на строительство')
