# Технологическое присоединение к электрическим сетям
pool_main, lanes_main = DIAGRAM.add_pool(ROOT_PROCESS_ID, ['Заявитель', 'Отдел по работе с клиентами', 'Технический отдел', 'Главный инженер', 'Оперативный персонал'], 'Сетевая организация')
pool_contractor = DIAGRAM.add_black_box_pool('Подрядная организация')
build = DIAGRAM.create_subprocess('Построить сетевые объекты', lanes_main[2])
apply = DIAGRAM.add_user_task('Подать заявку на присоединение', lanes_main[0])
check_docs = DIAGRAM.add_user_task('Проверить комплектность документов', lanes_main[1])
gw_docs = DIAGRAM.add_exclusive_gateway('Документы в порядке?', lanes_main[1])
notify_docs = DIAGRAM.add_send_task('Уведомить о недостающих документах', lanes_main[1])
add_docs = DIAGRAM.add_user_task('Дополнить документы', lanes_main[0])
check_power = DIAGRAM.add_task('Проверить свободную мощность', lanes_main[2])
gw_power = DIAGRAM.add_exclusive_gateway('Мощности достаточно?', lanes_main[2])
plan_upgrade = DIAGRAM.add_task('Разработать мероприятие по увеличению мощности', lanes_main[2])
approve_upgrade = DIAGRAM.add_user_task('Согласовать мероприятие', lanes_main[3])
gw_power_join = DIAGRAM.add_exclusive_gateway('', lanes_main[2])
p1 = DIAGRAM.add_parallel_gateway('', lanes_main[2])
tu = DIAGRAM.add_task('Подготовить технические условия', lanes_main[2])
fee = DIAGRAM.add_service_task('Рассчитать плату за присоединение', lanes_main[1])
p1_join = DIAGRAM.add_parallel_gateway('', lanes_main[1])
send_contract = DIAGRAM.add_send_task('Направить договор и ТУ', lanes_main[1])
sign_pay = DIAGRAM.add_user_task('Подписать договор и оплатить', lanes_main[0])
p2 = DIAGRAM.add_parallel_gateway('', lanes_main[2])
own_side = DIAGRAM.add_manual_task('Выполнить мероприятия на своей стороне', lanes_main[0])
p2_join = DIAGRAM.add_parallel_gateway('', lanes_main[2])
inspect = DIAGRAM.add_manual_task('Провести осмотр электроустановки', lanes_main[2])
gw_remarks = DIAGRAM.add_exclusive_gateway('Есть замечания?', lanes_main[2])
fix = DIAGRAM.add_manual_task('Устранить замечания', lanes_main[0])
connect = DIAGRAM.add_manual_task('Подать напряжение', lanes_main[4])
act = DIAGRAM.add_send_task('Оформить и направить акт о присоединении', lanes_main[1])
b1 = DIAGRAM.add_task('Выполнить проектирование', build)
b2 = DIAGRAM.add_task('Выполнить строительно-монтажные работы', build)
b3 = DIAGRAM.add_task('Сдать объекты сетевой организации', build)
DIAGRAM.add_link(ROOT_START_TASK_ID, apply)
DIAGRAM.add_link(apply, check_docs)
DIAGRAM.add_link(check_docs, gw_docs)
DIAGRAM.add_link(gw_docs, check_power, 'Да')
DIAGRAM.add_link(gw_docs, notify_docs, 'Нет')
DIAGRAM.add_link(notify_docs, add_docs)
DIAGRAM.add_link(add_docs, check_docs)
DIAGRAM.add_link(check_power, gw_power)
DIAGRAM.add_link(gw_power, gw_power_join, 'Да')
DIAGRAM.add_link(gw_power, plan_upgrade, 'Нет')
DIAGRAM.add_link(plan_upgrade, approve_upgrade)
DIAGRAM.add_link(approve_upgrade, gw_power_join)
DIAGRAM.add_link(gw_power_join, p1)
DIAGRAM.add_link(p1, tu)
DIAGRAM.add_link(p1, fee)
DIAGRAM.add_link(tu, p1_join)
DIAGRAM.add_link(fee, p1_join)
DIAGRAM.add_link(p1_join, send_contract)
DIAGRAM.add_link(send_contract, sign_pay)
DIAGRAM.add_link(sign_pay, p2)
DIAGRAM.add_link(p2, build)
DIAGRAM.add_link(p2, own_side)
DIAGRAM.add_link(build, p2_join)
DIAGRAM.add_link(own_side, p2_join)
DIAGRAM.add_link(p2_join, inspect)
DIAGRAM.add_link(inspect, gw_remarks)
DIAGRAM.add_link(gw_remarks, fix, 'Да')
DIAGRAM.add_link(fix, inspect)
DIAGRAM.add_link(gw_remarks, connect, 'Нет')
DIAGRAM.add_link(connect, act)
DIAGRAM.add_link(act, ROOT_END_TASK_ID)
DIAGRAM.add_link(b1, b2)
DIAGRAM.add_link(b2, b3)
DIAGRAM.add_message_link(build, pool_contractor, 'Заказ на строительство')
