# Выдача потребительского кредита
pool_main, lanes_main = DIAGRAM.add_pool(ROOT_PROCESS_ID, ['Клиент', 'Банковская система', 'Служба безопасности', 'Кредитный менеджер', 'Кредитный комитет', 'Бухгалтерия'], 'Банк')
pool_bki = DIAGRAM.add_black_box_pool('Бюро кредитных историй')
submit = DIAGRAM.add_user_task('Подать заявку на кредит', lanes_main[0])
check_form = DIAGRAM.add_service_task('Проверить полноту анкеты', lanes_main[1])
gw_full = DIAGRAM.add_exclusive_gateway('Анкета заполнена?', lanes_main[1])
req_more = DIAGRAM.add_send_task('Запросить недостающие данные', lanes_main[1])
fill = DIAGRAM.add_user_task('Дополнить анкету', lanes_main[0])
par_split = DIAGRAM.add_parallel_gateway('', lanes_main[1])
blacklist = DIAGRAM.add_task('Проверить по чёрным спискам', lanes_main[2])
history = DIAGRAM.add_service_task('Запросить кредитную историю', lanes_main[1])
par_join = DIAGRAM.add_parallel_gateway('', lanes_main[3])
assess = DIAGRAM.add_user_task('Оценить платёжеспособность', lanes_main[3])
gw_sum = DIAGRAM.add_exclusive_gateway('Сумма больше 1 млн?', lanes_main[3])
committee_decide = DIAGRAM.add_task('Принять решение комитетом', lanes_main[4])
manager_decide = DIAGRAM.add_user_task('Принять решение по кредиту', lanes_main[3])
gw_dec_join = DIAGRAM.add_exclusive_gateway('', lanes_main[3])
gw_approved = DIAGRAM.add_exclusive_gateway('Кредит одобрен?', lanes_main[3])
notify_reject = DIAGRAM.add_send_task('Уведомить об отказе', lanes_main[1])
end_reject = DIAGRAM.add_end_event('Кредит не выдан', lanes_main[1], None)
contract = DIAGRAM.add_user_task('Подготовить договор', lanes_main[3])
sign = DIAGRAM.add_user_task('Подписать договор', lanes_main[0])
transfer = DIAGRAM.add_task('Перечислить деньги на счёт', lanes_main[5])
DIAGRAM.add_link(ROOT_START_TASK_ID, submit)
DIAGRAM.add_link(submit, check_form)
DIAGRAM.add_link(check_form, gw_full)
DIAGRAM.add_link(gw_full, par_split, 'Да')
DIAGRAM.add_link(gw_full, req_more, 'Нет')
DIAGRAM.add_link(req_more, fill)
DIAGRAM.add_link(fill, check_form)
DIAGRAM.add_link(par_split, blacklist)
DIAGRAM.add_link(par_split, history)
DIAGRAM.add_link(blacklist, par_join)
DIAGRAM.add_link(history, par_join)
DIAGRAM.add_link(par_join, assess)
DIAGRAM.add_link(assess, gw_sum)
DIAGRAM.add_link(gw_sum, committee_decide, 'Да')
DIAGRAM.add_link(gw_sum, manager_decide, 'Нет')
DIAGRAM.add_link(committee_decide, gw_dec_join)
DIAGRAM.add_link(manager_decide, gw_dec_join)
DIAGRAM.add_link(gw_dec_join, gw_approved)
DIAGRAM.add_link(gw_approved, contract, 'Да')
DIAGRAM.add_link(gw_approved, notify_reject, 'Нет')
DIAGRAM.add_link(notify_reject, end_reject)
DIAGRAM.add_link(contract, sign)
DIAGRAM.add_link(sign, transfer)
DIAGRAM.add_link(transfer, ROOT_END_TASK_ID)
DIAGRAM.add_message_link(history, pool_bki, 'Запрос кредитной истории')
