# Выдача потребительского кредита
pool_main, lanes_main = DIAGRAM.add_pool(ROOT_PROCESS_ID, ['Клиент', 'Банковская система', 'Служба безопасности', 'Кредитный менеджер', 'Кредитный комитет', 'Бухгалтерия'], 'Банк')
pool_external_0 = DIAGRAM.add_black_box_pool('Бюро кредитных историй')
node_0 = DIAGRAM.add_user_task('Подать заявку на кредит', lanes_main[0], id='submit')
node_1 = DIAGRAM.add_service_task('Проверить полноту анкеты', lanes_main[1], id='check_form')
node_2 = DIAGRAM.add_exclusive_gateway('Анкета заполнена?', lanes_main[1], id='gw_full')
node_3 = DIAGRAM.add_send_task('Запросить недостающие данные', lanes_main[1], id='req_more')
node_4 = DIAGRAM.add_user_task('Дополнить анкету', lanes_main[0], id='fill')
node_5 = DIAGRAM.add_parallel_gateway('', lanes_main[1], id='par_split')
node_6 = DIAGRAM.add_task('Проверить по чёрным спискам', lanes_main[2], id='blacklist')
node_7 = DIAGRAM.add_service_task('Запросить кредитную историю', lanes_main[1], id='history')
node_8 = DIAGRAM.add_parallel_gateway('', lanes_main[3], id='par_join')
node_9 = DIAGRAM.add_user_task('Оценить платёжеспособность', lanes_main[3], id='assess')
node_10 = DIAGRAM.add_exclusive_gateway('Сумма больше 1 млн?', lanes_main[3], id='gw_sum')
node_11 = DIAGRAM.add_task('Принять решение комитетом', lanes_main[4], id='committee_decide')
node_12 = DIAGRAM.add_user_task('Принять решение по кредиту', lanes_main[3], id='manager_decide')
node_13 = DIAGRAM.add_exclusive_gateway('', lanes_main[3], id='gw_dec_join')
node_14 = DIAGRAM.add_exclusive_gateway('Кредит одобрен?', lanes_main[3], id='gw_approved')
node_15 = DIAGRAM.add_send_task('Уведомить об отказе', lanes_main[1], id='notify_reject')
node_16 = DIAGRAM.add_end_event('Кредит не выдан', lanes_main[1], None, id='end_reject')
node_17 = DIAGRAM.add_user_task('Подготовить договор', lanes_main[3], id='contract')
node_18 = DIAGRAM.add_user_task('Подписать договор', lanes_main[0], id='sign')
node_19 = DIAGRAM.add_task('Перечислить деньги на счёт', lanes_main[5], id='transfer')
DIAGRAM.add_link(ROOT_START_TASK_ID, node_0)
DIAGRAM.add_link(node_0, node_1)
DIAGRAM.add_link(node_1, node_2)
DIAGRAM.add_link(node_2, node_5, 'Да')
DIAGRAM.add_link(node_2, node_3, 'Нет', default=True)
DIAGRAM.add_link(node_3, node_4)
DIAGRAM.add_link(node_4, node_1)
DIAGRAM.add_link(node_5, node_6)
DIAGRAM.add_link(node_5, node_7)
DIAGRAM.add_link(node_6, node_8)
DIAGRAM.add_link(node_7, node_8)
DIAGRAM.add_link(node_8, node_9)
DIAGRAM.add_link(node_9, node_10)
DIAGRAM.add_link(node_10, node_11, 'Да')
DIAGRAM.add_link(node_10, node_12, 'Нет', default=True)
DIAGRAM.add_link(node_11, node_13)
DIAGRAM.add_link(node_12, node_13)
DIAGRAM.add_link(node_13, node_14)
DIAGRAM.add_link(node_14, node_17, 'Да')
DIAGRAM.add_link(node_14, node_15, 'Нет', default=True)
DIAGRAM.add_link(node_15, node_16)
DIAGRAM.add_link(node_17, node_18)
DIAGRAM.add_link(node_18, node_19)
DIAGRAM.add_link(node_19, ROOT_END_TASK_ID)
DIAGRAM.add_message_link(node_7, pool_external_0, 'Запрос кредитной истории')
