"""Orchestration.

Main mode ("ir"):
  text/document → [PII masking] → [LLM: IR extraction, structured output by JSON Schema]
  → [IR check: schema + references + linter + clarifying questions]
  → [deterministic BPMN builder: IR → DIAGRAM code → graph] → [auto layout (DI)]
  → [XSD validation + semantic validator + linter] → [self-repair: deterministic fixes, then LLM
  repairs the IR, ≤ max_repairs] → honest report of what is left.
The LLM never writes XML. Legacy mode ("two_stage" / "direct"): the LLM writes DIAGRAM API code
from the IR (kept for the original hackathon requirement "Python code generated by the model").
"""
from __future__ import annotations

import json
import time
from dataclasses import dataclass, field

from . import pii
from .bpmn.layout import layout
from .bpmn.serializer import to_xml
from .bpmn.validator import Issue, errors_of, format_issues_for_llm, normalize, validate
from .bpmn.xsd import validate_xsd
from .ir.diff import describe, diff_plans
from .ir.graph import IRGraph
from .ir.lint import LintIssue, autofix, lint, questions as lint_questions, summary as lint_summary
from .ir.merge import merge_plans, split_text
from .llm import prompts
from .llm.client import LLMClient, LLMError
from .llm.plan import Plan, PlanError, compile_plan, ir_json_schema, parse_plan
from .runlog import RunLog
from .sandbox import SandboxError, run_code

MAX_PLAN_REPAIRS = 2
MIN_TEXT = 15
MAX_TEXT = 200_000          # hard limit for one request
CHUNK_CHARS = 8_000         # longer texts are processed in parts


class InputError(ValueError):
    """Bad user input: a clear message instead of a crash."""


def check_text(text: str) -> str:
    text = (text or "").replace("\r\n", "\n").replace("\x00", "").strip()
    if not text:
        raise InputError("Описание пустое. Опишите процесс: кто участвует, какие шаги и условия.")
    letters = sum(ch.isalpha() for ch in text)
    if len(text) < MIN_TEXT or letters < 10:
        raise InputError("Описание слишком короткое: опишите хотя бы участников и 2–3 шага процесса.")
    if len(text) > MAX_TEXT:
        raise InputError(f"Текст слишком длинный ({len(text)} символов, максимум {MAX_TEXT}). "
                         "Разделите документ на несколько процессов.")
    return text


@dataclass
class BuildResult:
    ok: bool
    code: str
    xml: str | None = None
    issues: list[Issue] = field(default_factory=list)
    xsd_errors: list[str] = field(default_factory=list)
    error: str | None = None          # sandbox error
    stats: dict = field(default_factory=dict)

    def errors_for_llm(self) -> str:
        if self.error:
            return self.error
        parts = [format_issues_for_llm(self.issues)]
        if self.xsd_errors:
            parts.append("Ошибки XSD:\n" + "\n".join(self.xsd_errors[:10]))
        return "\n".join(p for p in parts if p)


def build(code: str, title: str = "Процесс", lenient: bool = False) -> BuildResult:
    """Deterministic part: code → graph → normalize → validate → layout → XML → XSD."""
    try:
        res = run_code(code, title)
    except SandboxError as e:
        return BuildResult(False, code, error=e.render())
    d = res.diagram
    issues = normalize(d, lenient=lenient)
    issues += validate(d)
    errs = errors_of(issues)
    if errs and not lenient:
        return BuildResult(False, code, issues=issues, stats=d.stats())
    xml = to_xml(d, layout(d))
    xsd_errors = validate_xsd(xml)
    return BuildResult(not errs and not xsd_errors, code, xml, issues, xsd_errors, stats=d.stats())


def build_ir(plan: Plan, lenient: bool = False, annotate_assumptions: bool = False) -> BuildResult:
    """Deterministic BPMN builder from the IR."""
    return build(compile_plan(plan, annotate_assumptions), plan.title, lenient=lenient)


def ir_problems(plan: Plan, result: BuildResult | None, issues: list[LintIssue]) -> list[str]:
    """Blocking problems for the self-repair loop (ids are IR ids)."""
    out = [f"[{i.code}] {i.message} Подсказка: {i.hint}" for i in issues if i.level == "error"]
    if result is not None:
        if result.error:
            out.append(f"[BUILD] {result.error}")
        lint_codes = {i.code[2:] for i in issues if i.level == "error"}
        out += [f"[{i.code}] {i.message}" for i in result.issues
                if i.level == "error" and i.code[2:] not in lint_codes]
        out += [f"[XSD] {e}" for e in result.xsd_errors[:10]]
    return out


def hide_people(plan: Plan) -> Plan:
    """Copy of the IR for the model: the performers directory keeps ids and roles, but names,
    positions and contacts are replaced. Regex PII masking alone would miss names like "Пётр Петров"."""
    if not plan.performers:
        return plan
    out = plan.model_copy(deep=True)
    for i, person in enumerate(out.performers, 1):
        person.name, person.position, person.contacts = f"Исполнитель {i}", "", ""
    return out


def restore_people(plan: Plan, original: list) -> Plan:
    """Put the real performer records back (by id) after the model answered."""
    real = {p.id: p for p in original}
    if not real and not plan.performers:
        return plan
    plan = plan.model_copy(deep=True)
    plan.performers = [real.get(p.id, p) for p in plan.performers]
    known = {p.id for p in plan.performers}
    plan.performers += [p for pid, p in real.items() if pid not in known and
                        any(e.performer == pid for e in plan.elements)]
    for e in plan.elements:
        if e.performer and e.performer not in {p.id for p in plan.performers}:
            e.performer = None
    return plan


@dataclass
class PipelineResult:
    ok: bool
    xml: str | None
    code: str
    plan: dict | None
    issues: list[dict]
    xsd_errors: list[str]
    attempts: list[dict]
    stats: dict
    assumptions: list[str]
    questions: list[str]
    run_id: str
    duration_s: float
    source: str      # ir | ir_autofix | ir_repaired | reviewed_plan | llm | llm_repaired | plan_compiler | lenient | questions | error
    message: str = ""
    summary: str = ""
    lint: list[dict] = field(default_factory=list)
    lint_summary: dict = field(default_factory=dict)
    clarifications: list[dict] = field(default_factory=list)
    residual: list[str] = field(default_factory=list)   # problems left after all repair attempts
    fixes: list[str] = field(default_factory=list)      # deterministic fixes applied
    pii: list[dict] = field(default_factory=list)       # what was masked before sending to the LLM
    diff: dict | None = None
    needs_answers: bool = False

    def to_dict(self) -> dict:
        return self.__dict__.copy()


def _strip_fences(text: str) -> str:
    t = text.strip()
    if "```" in t:
        start = t.find("```")
        nl = t.find("\n", start)
        end = t.find("```", nl + 1)
        if nl != -1:
            t = t[nl + 1:end if end != -1 else None]
    return t.strip() + "\n"


class Pipeline:
    def __init__(self, llm: LLMClient | None, runs_dir=None, max_repairs: int = 3, settings=None,
                 repair_llm: LLMClient | None = None):
        self.llm = llm
        self.repair_llm = repair_llm
        self.runs_dir = runs_dir
        self.max_repairs = max_repairs
        self.settings = settings
        self.llm_error: str | None = None     # why the LLM client could not be created

    # ------------------------------------------------------------------ helpers
    def _mask(self, text: str) -> tuple[str, list]:
        s = self.settings
        if s is not None and not s.pii_mask:
            return text, []
        return pii.mask(text, addresses=bool(s and s.pii_mask_addresses), objects=bool(s and s.pii_mask_objects))

    def _ask(self, log: RunLog, stage: str, messages: list[dict], schema: dict | None = None,
             client: LLMClient | None = None) -> str:
        client = client or self.llm
        if client is None:
            raise LLMError("LLM не настроен: " + (self.llm_error or "задайте LLM_PROVIDER/LLM_API_KEY в .env"))
        resp = client.complete(messages, schema)
        log.llm(stage, messages, resp, schema=schema is not None)
        return resp.text

    @staticmethod
    def _ground_quotes(plan: Plan, text: str):
        for element in plan.elements:
            if element.source_quote and element.source_quote not in text:
                element.source_quote = ""
                element.assumption = (element.assumption + " Основание в исходном тексте не подтверждено.").strip()

    # ------------------------------------------------------------------ IR extraction
    def _extract_part(self, log: RunLog, attempts: list[dict], stage: str, user: str) -> tuple[Plan, list[dict]]:
        messages = [{"role": "system", "content": prompts.load("ir_extract.system")},
                    {"role": "user", "content": user}]
        last_err = None
        for i in range(MAX_PLAN_REPAIRS + 1):
            answer = self._ask(log, stage if i == 0 else f"{stage}_json_repair_{i}", messages, ir_json_schema())
            try:
                plan = parse_plan(answer)
                attempts.append({"stage": stage, "ok": True})
                return plan, messages
            except PlanError as e:
                last_err = str(e)
                attempts.append({"stage": stage, "ok": False, "error": last_err})
                messages = messages + [{"role": "assistant", "content": answer[:6000]},
                                       {"role": "user", "content": prompts.render("ir_repair.user", errors=last_err)}]
        raise PlanError(last_err or "Модель не вернула корректный IR")

    def extract_ir(self, text: str, log: RunLog, attempts: list[dict], ask: bool = False
                   ) -> tuple[Plan, list[dict], list]:
        """Returns (plan with real values restored, conversation prefix for repairs, masked items)."""
        log.prompts(prompts.used("ir_extract.system", "ir_extract.user", "ir_repair.user"))
        masked_text, items = self._mask(text)
        hint = ("Режим уточнений: не домысливай — неясное записывай в questions." if ask else
                "Режим без уточнений: при неясности сделай разумное допущение и запиши его в assumption "
                "элемента и в assumptions.")
        parts = split_text(masked_text, CHUNK_CHARS)
        if len(parts) == 1:
            user = prompts.render("ir_extract.user", text=masked_text, mode_hint=hint)
            plan, conv = self._extract_part(log, attempts, "extract_ir", user)
        else:
            log.prompts(prompts.used("ir_merge.user"))
            plans, known = [], []
            for k, part in enumerate(parts):
                user = prompts.render("ir_merge.user", part=k + 1, total=len(parts), text=part,
                                      known_participants=json.dumps(known, ensure_ascii=False))
                p, _ = self._extract_part(log, attempts, f"extract_ir_part{k + 1}", user)
                known += [{"id": x.id, "name": x.name} for x in p.participants
                          if x.id not in {y["id"] for y in known}]
                plans.append(p)
            plan = merge_plans(plans)
            attempts.append({"stage": "merge_parts", "ok": True, "error": f"частей: {len(parts)}"})
            conv = [{"role": "system", "content": prompts.load("ir_extract.system")},
                    {"role": "user", "content": "Документ обработан частями; ниже объединённый IR."}]
        if items:
            plan = Plan.model_validate(pii.unmask(plan.model_dump(by_alias=True), items))
        self._ground_quotes(plan, text)
        log.write("ir.json", plan.model_dump_json(indent=2, by_alias=True))
        return plan, conv, items

    # ------------------------------------------------------------------ build + self-repair
    def _repair_loop(self, plan: Plan, conv: list[dict], log: RunLog, attempts: list[dict],
                     annotate: bool = False, masked: list | None = None):
        """Build the IR; on problems apply deterministic fixes, then let the LLM repair the IR.
        Returns (plan, BuildResult, lint issues, source, applied fixes, residual problems)."""
        fixes: list[str] = []
        source = "ir"
        llm_rounds = 0
        while True:
            issues = lint(plan)
            result = build_ir(plan, annotate_assumptions=annotate)
            problems = ir_problems(plan, result, issues)
            attempts.append({"stage": "build" if not llm_rounds and not fixes else "rebuild",
                             "ok": not problems, "error": "\n".join(problems) or None})
            if not problems:
                return plan, result, issues, source, fixes, []
            fixed, applied = _safe_autofix(plan)
            if applied:
                plan, fixes = fixed, fixes + applied
                source = "ir_autofix" if source == "ir" else source
                attempts.append({"stage": "autofix", "ok": True, "error": "; ".join(applied)})
                issues = lint(plan)
                result = build_ir(plan, annotate_assumptions=annotate)
                problems = ir_problems(plan, result, issues)
                if not problems:
                    return plan, result, issues, source, fixes, []
            if llm_rounds >= self.max_repairs or (self.llm is None and self.repair_llm is None) or not conv:
                break
            llm_rounds += 1
            text_errors = "\n".join(f"- {p}" for p in problems)
            log.write(f"errors_{llm_rounds}.txt", text_errors)
            ir_json = hide_people(plan).model_dump_json(by_alias=True, exclude_defaults=True)
            if masked:
                ir_json = _remask(ir_json, masked)
            messages = conv[:2] + [{"role": "assistant", "content": ir_json},
                                   {"role": "user", "content": prompts.render("ir_repair.user", errors=text_errors)}]
            try:
                answer = self._ask(log, f"repair_{llm_rounds}", messages, ir_json_schema(),
                                   client=self.repair_llm or self.llm)
                new_plan = parse_plan(answer)
                if masked:
                    new_plan = Plan.model_validate(pii.unmask(new_plan.model_dump(by_alias=True), masked))
                plan, source = restore_people(new_plan, plan.performers), "ir_repaired"
                attempts.append({"stage": f"repair_{llm_rounds}", "ok": True})
            except (PlanError, LLMError) as e:
                attempts.append({"stage": f"repair_{llm_rounds}", "ok": False, "error": str(e)})
        # exhausted: honest report + lenient build so the analyst still gets an editable draft
        issues = lint(plan)
        result = build_ir(plan, annotate_assumptions=annotate)
        residual = ir_problems(plan, result, issues)
        if not result.xml:
            lenient = build_ir(plan, lenient=True, annotate_assumptions=annotate)
            if lenient.xml:
                result, source = lenient, "lenient"
        return plan, result, issues, source, fixes, residual

    # ------------------------------------------------------------------ public entry points
    def generate(self, text: str, mode: str = "ir", ask: bool = False) -> PipelineResult:
        if mode in ("two_stage", "code", "direct"):
            return self.generate_code(text, "direct" if mode == "direct" else "two_stage")
        log = RunLog(self.runs_dir, "generate")
        t0 = time.time()
        attempts: list[dict] = []
        try:
            text = check_text(text)
            log.write("input.txt", text)
            plan, conv, masked = self.extract_ir(text, log, attempts, ask=ask)
        except (InputError, LLMError, PlanError) as e:
            log.finish(ok=False, error=str(e))
            return _error(log, t0, attempts, str(e))
        masked_info = [m.to_dict() for m in masked]
        issues = lint(plan)
        clar = lint_questions(plan, issues)
        if ask and any(q["blocking"] for q in clar):
            log.finish(ok=True, source="questions", questions=len(clar))
            return PipelineResult(True, None, "", plan.model_dump(by_alias=True), [], [], attempts, {},
                                  plan.assumptions, [q["question"] for q in clar], log.id,
                                  round(time.time() - t0, 2), "questions",
                                  "Нужны уточнения: ответьте на вопросы или постройте черновик.",
                                  lint=[i.to_dict() for i in issues], lint_summary=lint_summary(issues),
                                  clarifications=clar, pii=masked_info, needs_answers=True)
        plan, result, issues, source, fixes, residual = self._repair_loop(
            plan, conv, log, attempts, annotate=not ask, masked=masked)
        return self._finish(log, t0, result, plan, attempts, source, issues=issues, fixes=fixes,
                            residual=residual, pii_items=masked_info)

    def prepare(self, text: str) -> dict:
        """Guided mode: one extraction pass + clarifying questions, shown before building."""
        log = RunLog(self.runs_dir, "interview")
        attempts: list[dict] = []
        try:
            text = check_text(text)
            log.write("input.txt", text)
            plan, _, masked = self.extract_ir(text, log, attempts, ask=True)
            issues = lint(plan)
            clar = lint_questions(plan, issues)
            plan.questions = [q["question"] for q in clar]
            log.finish(ok=True, questions=len(clar))
            return {"ok": True, "plan": plan.model_dump(by_alias=True), "run_id": log.id,
                    "clarifications": clar, "lint": [i.to_dict() for i in issues],
                    "pii": [m.to_dict() for m in masked]}
        except (InputError, LLMError, PlanError) as e:
            log.finish(ok=False, error=str(e))
            return {"ok": False, "message": str(e), "run_id": log.id}

    def from_plan(self, plan: Plan, text: str = "", annotate: bool = False) -> PipelineResult:
        """Build a reviewed / template / edited IR deterministically (no model calls)."""
        log = RunLog(self.runs_dir, "reviewed_plan")
        t0 = time.time()
        if text:
            self._ground_quotes(plan, text)
        log.write("input.txt", text)
        log.write("ir.json", plan.model_dump_json(indent=2, by_alias=True))
        attempts: list[dict] = []
        plan, result, issues, source, fixes, residual = self._repair_loop(plan, [], log, attempts, annotate)
        source = "reviewed_plan" if source == "ir" else source
        return self._finish(log, t0, result, plan, attempts, source, issues=issues, fixes=fixes, residual=residual)

    def refine(self, text: str, instruction: str, plan: Plan | None = None, xml: str | None = None,
               code: str = "") -> PipelineResult:
        """Dialogue edit: the LLM changes the IR (not XML); the result is rebuilt and diffed."""
        from .ir.from_diagram import xml_to_plan
        log = RunLog(self.runs_dir, "refine")
        t0 = time.time()
        attempts: list[dict] = []
        log.write("instruction.txt", instruction or "")
        items: list = []
        try:
            instruction = (instruction or "").strip()
            if len(instruction) < 2:
                raise InputError("Опишите, что изменить в схеме.")
            if xml:
                before = xml_to_plan(xml)          # keeps the analyst's manual canvas edits
            elif plan is not None:
                before = plan
            elif code:
                return self.refine_code(text, code, instruction)
            else:
                raise InputError("Нет текущей диаграммы для изменения")
            log.write("ir_before.json", before.model_dump_json(indent=2, by_alias=True))
            log.prompts(prompts.used("ir_edit.system", "ir_edit.user", "ir_repair.user"))
            g = IRGraph.build(before)
            steps = "\n".join(f"{i}. {g.name(n)} ({n})" for i, n in g.numbered_steps())
            ir_json = hide_people(before).model_dump_json(by_alias=True, exclude_defaults=True)
            masked_instr, items = self._mask(instruction)
            ir_masked, more = self._mask(_remask(ir_json, items) if items else ir_json)
            items += [m for m in more if m.token not in {x.token for x in items}]
            messages = [{"role": "system", "content": prompts.load("ir_edit.system")},
                        {"role": "user", "content": prompts.render("ir_edit.user", ir=ir_masked,
                                                                    numbered_steps=steps, instruction=masked_instr)}]
            answer = self._ask(log, "edit_ir", messages, ir_json_schema())
            summary_text = _changes_summary(answer)
            try:
                after = parse_plan(answer)
            except PlanError as e:
                attempts.append({"stage": "edit_ir", "ok": False, "error": str(e)})
                messages = messages + [{"role": "assistant", "content": answer[:6000]},
                                       {"role": "user", "content": prompts.render("ir_repair.user", errors=str(e))}]
                after = parse_plan(self._ask(log, "edit_ir_json_repair", messages, ir_json_schema()))
            if items:
                after = Plan.model_validate(pii.unmask(after.model_dump(by_alias=True), items))
            after = restore_people(after, before.performers)
            attempts.append({"stage": "edit_ir", "ok": True})
        except (InputError, LLMError, PlanError) as e:
            log.finish(ok=False, error=str(e))
            return _error(log, t0, attempts, str(e))
        after, result, issues, source, fixes, residual = self._repair_loop(after, messages[:2], log, attempts,
                                                                           masked=items)
        d = diff_plans(before, after)
        res = self._finish(log, t0, result, after, attempts, source, issues=issues, fixes=fixes,
                           residual=residual, pii_items=[m.to_dict() for m in items])
        res.diff = d
        res.summary = summary_text or describe(d)
        return res

    # ------------------------------------------------------------------ assistant tools (LLM + fallback)
    def _tool_ask(self, kind: str, prompt: str, payload: str, schema: dict | None) -> tuple[str | None, str]:
        """One LLM call for an auxiliary tool; returns (answer or None, run_id). Never raises."""
        log = RunLog(self.runs_dir, kind)
        if self.llm is None:
            log.finish(ok=False, error="LLM не настроен")
            return None, log.id
        log.prompts(prompts.used(prompt))
        masked, _ = self._mask(payload)
        try:
            answer = self._ask(log, kind, [{"role": "system", "content": prompts.load(prompt)},
                                           {"role": "user", "content": masked}], schema)
            log.finish(ok=True)
            return answer, log.id
        except LLMError as e:
            log.finish(ok=False, error=str(e))
            return None, log.id

    def explain(self, plan: Plan, use_llm: bool = True) -> dict:
        from .ir.sop import plain_explanation
        if use_llm:
            answer, run_id = self._tool_ask("explain", "explain.system",
                                            hide_people(plan).model_dump_json(by_alias=True, exclude_defaults=True), None)
            if answer and len(answer.strip()) > 40:
                return {"text": answer.strip(), "source": "llm", "run_id": run_id}
        return {"text": plain_explanation(plan), "source": "rules"}

    def estimate(self, plan: Plan) -> dict:
        """LLM proposes durations for steps without them; values are marked estimate=true."""
        from .ir.analytics import TYPICAL
        from .ir.graph import TASK_TYPES
        todo = [e for e in plan.elements if (e.type in TASK_TYPES or e.type in ("timer_event", "message_event"))
                and e.duration_min is None]
        if not todo:
            return {"plan": plan, "source": "given", "estimated": [], "comments": {}}
        payload = json.dumps({"process": plan.title, "steps": [
            {"id": e.id, "name": e.name, "type": e.type, "performer": e.participant, "deadline": e.deadline}
            for e in todo]}, ensure_ascii=False)
        schema = {"type": "object", "properties": {"estimates": {"type": "array", "items": {
            "type": "object", "properties": {"id": {"type": "string"}, "duration_min": {"type": "number"},
                                             "wait_min": {"type": "number"}, "comment": {"type": "string"}},
            "required": ["id", "duration_min"]}}}, "required": ["estimates"]}
        answer, run_id = self._tool_ask("estimate", "estimate.system", payload, schema)
        got, comments, source = {}, {}, "typical"
        if answer:
            try:
                for item in json.loads(answer[answer.find("{"):answer.rfind("}") + 1]).get("estimates", []):
                    d, w = float(item.get("duration_min", -1)), float(item.get("wait_min", 0) or 0)
                    if item.get("id") and 0 <= d <= 60 * 24 * 365 and 0 <= w <= 60 * 24 * 365:
                        got[item["id"]] = (d, w)
                        comments[item["id"]] = str(item.get("comment", ""))[:300]
                source = "llm" if got else "typical"
            except (ValueError, TypeError, AttributeError):
                got = {}
        data = plan.model_dump(by_alias=True)
        done = []
        for e in data["elements"]:
            if e["id"] in {x.id for x in todo}:
                d, w = got.get(e["id"], TYPICAL.get(e["type"], (30, 0)))
                e["duration_min"], e["wait_min"], e["estimate"] = d, w, True
                done.append(e["id"])
        return {"plan": Plan.model_validate(data), "source": source, "estimated": done, "comments": comments,
                "run_id": run_id if answer else None}

    def recommend(self, plan: Plan, analysis: dict, issues: list[LintIssue]) -> dict:
        sim = analysis["simulation"]
        top = sorted(analysis["heat"]["values"].items(), key=lambda kv: -kv[1])[:5]
        g = IRGraph.build(plan)
        facts = {"process": plan.title, "mean_min": sim["mean_min"], "p90_min": sim["p90_min"],
                 "critical_path": [g.name(n) for n in analysis["critical_path"]["path"]],
                 "slowest_steps": [{"id": n, "name": g.name(n), "minutes": v} for n, v in top],
                 "utilization": sim["utilization"][:5], "branches": sim["branches"][:6],
                 "lint": [i.message for i in issues if i.level != "info"][:10]}
        schema = {"type": "object", "properties": {"recommendations": {"type": "array", "items": {
            "type": "object", "properties": {k: {"type": "string"} for k in ("title", "rationale", "action", "effect")}
            | {"elements": {"type": "array", "items": {"type": "string"}}}, "required": ["title", "action"]}}},
            "required": ["recommendations"]}
        answer, run_id = self._tool_ask("recommend", "recommend.system",
                                        json.dumps({"ir": hide_people(plan).model_dump(by_alias=True, exclude_defaults=True),
                                                    "facts": facts}, ensure_ascii=False), schema)
        recs = []
        if answer:
            try:
                recs = json.loads(answer[answer.find("{"):answer.rfind("}") + 1]).get("recommendations", [])[:8]
                recs = [r for r in recs if isinstance(r, dict) and r.get("title")]
            except (ValueError, AttributeError):
                recs = []
        source = "llm" if recs else "rules"
        if not recs:
            for n, v in top[:2]:
                recs.append({"title": f"Сократить время шага «{g.name(n)}»",
                             "rationale": f"Один из самых долгих шагов (≈{v:.0f} мин с ожиданием).",
                             "action": "Проверьте причины ожидания: очередь, согласования, нехватка исполнителей.",
                             "effect": "оценка: сокращение общего времени процесса", "elements": [n]})
            for b in sim["branches"]:
                for br in b["branches"]:
                    loop = any(br["to"] == f.target and (f.source, f.target) in g.back_edges() for f in g.out[b["gateway"]])
                    if loop and br["share"] > 0.15:
                        recs.append({"title": f"Снизить долю возвратов на «{b['name']}»",
                                     "rationale": f"Возврат на доработку в {br['share']:.0%} случаев.",
                                     "action": "Добавьте чек-лист или проверку на входе, чтобы ошибки находились раньше.",
                                     "effect": "оценка: меньше повторных циклов", "elements": [b["gateway"]]})
            if sim["utilization"]:
                u = sim["utilization"][0]
                recs.append({"title": f"Разгрузить участника «{u['name']}»",
                             "rationale": f"Занят {u['share_of_time']:.0%} времени процесса — вероятное узкое место.",
                             "action": "Перераспределите часть шагов или автоматизируйте рутинные операции.",
                             "effect": "оценка: снижение p90", "elements": []})
        for r in recs:
            r["kind"] = "рекомендация, не факт"
        return {"recommendations": recs, "source": source, "run_id": run_id if answer else None}

    # ------------------------------------------------------------------ legacy: LLM writes DIAGRAM code
    def _code_loop(self, log: RunLog, system: str, messages: list[dict], title: str,
                   attempts: list[dict]) -> tuple[BuildResult, int]:
        result = None
        conv = [{"role": "system", "content": system}] + messages
        for i in range(self.max_repairs + 1):
            stage = "codegen" if i == 0 else f"repair_{i}"
            client = self.llm if i == 0 else (self.repair_llm or self.llm)
            code = _strip_fences(self._ask(log, stage, conv, None, client=client))
            log.write(f"code_{i}.py", code)
            result = build(code, title)
            attempts.append({"stage": stage, "ok": result.ok, "code": code,
                             "error": None if result.ok else result.errors_for_llm()})
            if result.ok:
                return result, i
            log.write(f"errors_{i}.txt", result.errors_for_llm())
            conv = conv + [
                {"role": "assistant", "content": code},
                {"role": "user", "content": prompts.REPAIR_USER.format(code=code, errors=result.errors_for_llm())},
            ]
        return result, self.max_repairs

    def generate_code(self, text: str, mode: str = "two_stage") -> PipelineResult:
        log = RunLog(self.runs_dir, "generate_code")
        t0 = time.time()
        attempts: list[dict] = []
        plan: Plan | None = None
        title = "Процесс"
        try:
            text = check_text(text)
            log.write("input.txt", text)
            log.prompts(prompts.used("code_generate.system", "code_direct.system", "code_repair.user"))
            if mode == "two_stage":
                plan, _, _ = self.extract_ir(text, log, attempts)
                title = plan.title
                plan_json = plan.model_dump_json(indent=1, by_alias=True, exclude_none=True)
                system = prompts.CODEGEN_SYSTEM
                messages = [{"role": "user", "content": prompts.CODEGEN_USER.format(plan=plan_json)}]
            else:
                masked_text, _ = self._mask(text)
                system = prompts.DIRECT_SYSTEM
                messages = [{"role": "user", "content": prompts.render("ir_extract.user", text=masked_text,
                                                                       mode_hint="Верни Python-код.")}]
            result, repairs = self._code_loop(log, system, messages, title, attempts)
            source = "llm" if repairs == 0 else "llm_repaired"
        except (InputError, LLMError, PlanError) as e:
            log.finish(ok=False, error=str(e))
            return _error(log, t0, attempts, str(e), plan)
        if not result.ok and plan is not None:
            fb = build_ir(plan)
            attempts.append({"stage": "plan_compiler", "ok": fb.ok, "code": fb.code,
                             "error": None if fb.ok else fb.errors_for_llm()})
            if fb.ok:
                result, source = fb, "plan_compiler"
        if not result.ok:
            lenient = build(result.code, title, lenient=True)
            if lenient.xml:
                result, source = lenient, "lenient"
        return self._finish(log, t0, result, plan, attempts, source, issues=lint(plan) if plan else None)

    def refine_code(self, text: str, code: str, instruction: str) -> PipelineResult:
        log = RunLog(self.runs_dir, "refine_code")
        log.write("input.txt", text)
        log.write("instruction.txt", instruction)
        log.write("code_before.py", code)
        t0 = time.time()
        attempts: list[dict] = []
        messages = [{"role": "user", "content": prompts.REFINE_USER.format(
            text=text or "(нет)", code=code, instruction=instruction)}]
        try:
            result, repairs = self._code_loop(log, prompts.REFINE_SYSTEM, messages, "Процесс", attempts)
            source = "llm" if repairs == 0 else "llm_repaired"
        except LLMError as e:
            log.finish(ok=False, error=str(e))
            return _error(log, t0, attempts, str(e))
        if not result.ok:
            lenient = build(result.code, "Процесс", lenient=True)
            if lenient.xml:
                result, source = lenient, "lenient"
        res = self._finish(log, t0, result, None, attempts, source)
        first = res.code.lstrip().splitlines()[0] if res.code.strip() else ""
        if first.startswith("# Изменения:"):
            res.summary = first[len("# Изменения:"):].strip()
        return res

    def from_code(self, code: str, kind: str = "code") -> PipelineResult:
        log = RunLog(self.runs_dir, kind)
        t0 = time.time()
        result = build(code)
        source = "manual"
        if not result.ok:
            lenient = build(code, lenient=True)
            if lenient.xml:
                result, source = lenient, "lenient"
        plan = None
        if result.xml:
            try:
                from .ir.from_diagram import xml_to_plan
                plan = xml_to_plan(result.xml)
            except Exception:  # noqa: BLE001 - the IR view is optional for imported files
                plan = None
        return self._finish(log, t0, result, plan, [{"stage": kind, "ok": result.ok}], source,
                            issues=lint(plan) if plan else None)

    # ------------------------------------------------------------------ result
    def _finish(self, log, t0, result: BuildResult, plan: Plan | None, attempts, source,
                issues: list[LintIssue] | None = None, fixes=None, residual=None, pii_items=None) -> PipelineResult:
        if result.xml:
            log.write("result.bpmn", result.xml)
        log.write("final_code.py", result.code)
        issues = issues or []
        clar = lint_questions(plan, issues) if plan else []
        res = PipelineResult(
            ok=result.xml is not None and not result.xsd_errors and not residual,
            xml=result.xml,
            code=result.code,
            plan=json.loads(plan.model_dump_json(by_alias=True)) if plan else None,
            issues=[i.to_dict() for i in result.issues],
            xsd_errors=result.xsd_errors,
            attempts=attempts,
            stats=result.stats,
            assumptions=plan.assumptions if plan else [],
            questions=[q["question"] for q in clar],
            run_id=log.id,
            duration_s=round(time.time() - t0, 2),
            source=source,
            message="" if result.xml else (result.errors_for_llm() or "Не удалось построить диаграмму"),
            lint=[i.to_dict() for i in issues],
            lint_summary=lint_summary(issues),
            clarifications=clar,
            residual=residual or [],
            fixes=fixes or [],
            pii=pii_items or [],
        )
        log.finish(ok=res.ok, source=source, stats=result.stats,
                   repairs=sum(1 for a in attempts if a["stage"].startswith("repair")),
                   errors=[i.to_dict() for i in result.issues if i.level == "error"],
                   lint=res.lint_summary, residual=res.residual, fixes=res.fixes,
                   xsd_errors=result.xsd_errors, pii_masked=len(res.pii))
        return res


def _safe_autofix(plan: Plan) -> tuple[Plan, list[str]]:
    try:
        return autofix(plan, codes={"E_NO_START", "E_NO_END", "E_DEAD_END", "E_END_OUTGOING", "E_NO_INCOMING",
                                    "E_DEADLOCK", "W_CROSS_POOL_FLOW"})
    except (PlanError, ValueError):
        return plan, []


def _changes_summary(answer: str) -> str:
    try:
        data = json.loads(answer[answer.find("{"):answer.rfind("}") + 1])
        return str(data.get("changes_summary") or "")
    except (ValueError, AttributeError):
        return ""


def _remask(text: str, items: list) -> str:
    """Replace original sensitive values with their tokens (IR sent back to the LLM)."""
    for m in sorted(items, key=lambda x: -len(x.original)):
        text = text.replace(m.original, m.token)
    return text


def _error(log: RunLog, t0: float, attempts, message: str, plan: Plan | None = None) -> PipelineResult:
    return PipelineResult(False, None, "", plan.model_dump(by_alias=True) if plan else None, [], [], attempts,
                          {}, [], [], log.id, round(time.time() - t0, 2), "error", message)
