# Устранение аварийного отключения электроэнергии
pool_main, lanes_main = DIAGRAM.add_pool(ROOT_PROCESS_ID, ['Абонент', 'Диспетчер', 'Информационная система', 'Аварийная бригада'], 'Электросетевая компания')
node_0 = DIAGRAM.add_task('Сообщить об отключении', lanes_main[0], id='report')
node_1 = DIAGRAM.add_user_task('Зарегистрировать обращение', lanes_main[1], id='register')
node_2 = DIAGRAM.add_user_task('Проверить данные телемеханики', lanes_main[1], id='telemetry')
node_3 = DIAGRAM.add_exclusive_gateway('Тип отключения?', lanes_main[1], id='gw_type')
node_4 = DIAGRAM.add_send_task('Сообщить сроки восстановления', lanes_main[1], id='inform')
node_5 = DIAGRAM.add_end_event('Обращение закрыто', lanes_main[1], None, id='end_planned')
node_6 = DIAGRAM.add_parallel_gateway('', lanes_main[1], id='p1')
node_7 = DIAGRAM.add_user_task('Сформировать наряд', lanes_main[1], id='order')
node_8 = DIAGRAM.add_service_task('Отправить SMS абонентам участка', lanes_main[2], id='sms')
node_9 = DIAGRAM.add_manual_task('Выехать на место аварии', lanes_main[3], id='go')
node_10 = DIAGRAM.add_manual_task('Локализовать повреждение', lanes_main[3], id='localize')
node_11 = DIAGRAM.add_manual_task('Устранить повреждение', lanes_main[3], id='repair')
node_12 = DIAGRAM.add_exclusive_gateway('Устранено за 4 часа?', lanes_main[3], id='gw_time')
node_13 = DIAGRAM.add_user_task('Подключить резервный источник питания', lanes_main[1], id='dgu')
node_14 = DIAGRAM.add_manual_task('Восстановить схему электроснабжения', lanes_main[3], id='restore')
node_15 = DIAGRAM.add_parallel_gateway('', lanes_main[1], id='p1_join')
node_16 = DIAGRAM.add_user_task('Проверить подачу напряжения', lanes_main[1], id='check_v')
node_17 = DIAGRAM.add_user_task('Закрыть наряд', lanes_main[1], id='close')
node_18 = DIAGRAM.add_service_task('Уведомить о восстановлении', lanes_main[2], id='sms_ok')
DIAGRAM.add_link(ROOT_START_TASK_ID, node_0)
DIAGRAM.add_link(node_0, node_1)
DIAGRAM.add_link(node_1, node_2)
DIAGRAM.add_link(node_2, node_3)
DIAGRAM.add_link(node_3, node_4, 'Плановое')
DIAGRAM.add_link(node_4, node_5)
DIAGRAM.add_link(node_3, node_6, 'Аварийное')
DIAGRAM.add_link(node_6, node_7)
DIAGRAM.add_link(node_6, node_8)
DIAGRAM.add_link(node_7, node_9)
DIAGRAM.add_link(node_9, node_10)
DIAGRAM.add_link(node_10, node_11)
DIAGRAM.add_link(node_11, node_12)
DIAGRAM.add_link(node_12, node_14, 'Да')
DIAGRAM.add_link(node_12, node_13, 'Нет', default=True)
DIAGRAM.add_link(node_13, node_11)
DIAGRAM.add_link(node_14, node_15)
DIAGRAM.add_link(node_8, node_15)
DIAGRAM.add_link(node_15, node_16)
DIAGRAM.add_link(node_16, node_17)
DIAGRAM.add_link(node_17, node_18)
DIAGRAM.add_link(node_18, ROOT_END_TASK_ID)
