# Устранение аварийного отключения электроэнергии
pool_main, lanes_main = DIAGRAM.add_pool(ROOT_PROCESS_ID, ['Абонент', 'Диспетчер', 'Информационная система', 'Аварийная бригада'], 'Электросетевая компания')
report = DIAGRAM.add_task('Сообщить об отключении', lanes_main[0])
register = DIAGRAM.add_user_task('Зарегистрировать обращение', lanes_main[1])
telemetry = DIAGRAM.add_user_task('Проверить данные телемеханики', lanes_main[1])
gw_type = DIAGRAM.add_exclusive_gateway('Тип отключения?', lanes_main[1])
inform = DIAGRAM.add_send_task('Сообщить сроки восстановления', lanes_main[1])
end_planned = DIAGRAM.add_end_event('Обращение закрыто', lanes_main[1], None)
p1 = DIAGRAM.add_parallel_gateway('', lanes_main[1])
order = DIAGRAM.add_user_task('Сформировать наряд', lanes_main[1])
sms = DIAGRAM.add_service_task('Отправить SMS абонентам участка', lanes_main[2])
go = DIAGRAM.add_manual_task('Выехать на место аварии', lanes_main[3])
localize = DIAGRAM.add_manual_task('Локализовать повреждение', lanes_main[3])
repair = DIAGRAM.add_manual_task('Устранить повреждение', lanes_main[3])
gw_time = DIAGRAM.add_exclusive_gateway('Устранено за 4 часа?', lanes_main[3])
dgu = DIAGRAM.add_user_task('Подключить резервный источник питания', lanes_main[1])
restore = DIAGRAM.add_manual_task('Восстановить схему электроснабжения', lanes_main[3])
p1_join = DIAGRAM.add_parallel_gateway('', lanes_main[1])
check_v = DIAGRAM.add_user_task('Проверить подачу напряжения', lanes_main[1])
close = DIAGRAM.add_user_task('Закрыть наряд', lanes_main[1])
sms_ok = DIAGRAM.add_service_task('Уведомить о восстановлении', lanes_main[2])
DIAGRAM.add_link(ROOT_START_TASK_ID, report)
DIAGRAM.add_link(report, register)
DIAGRAM.add_link(register, telemetry)
DIAGRAM.add_link(telemetry, gw_type)
DIAGRAM.add_link(gw_type, inform, 'Плановое')
DIAGRAM.add_link(inform, end_planned)
DIAGRAM.add_link(gw_type, p1, 'Аварийное')
DIAGRAM.add_link(p1, order)
DIAGRAM.add_link(p1, sms)
DIAGRAM.add_link(order, go)
DIAGRAM.add_link(go, localize)
DIAGRAM.add_link(localize, repair)
DIAGRAM.add_link(repair, gw_time)
DIAGRAM.add_link(gw_time, restore, 'Да')
DIAGRAM.add_link(gw_time, dgu, 'Нет')
DIAGRAM.add_link(dgu, repair)
DIAGRAM.add_link(restore, p1_join)
DIAGRAM.add_link(sms, p1_join)
DIAGRAM.add_link(p1_join, check_v)
DIAGRAM.add_link(check_v, close)
DIAGRAM.add_link(close, sms_ok)
DIAGRAM.add_link(sms_ok, ROOT_END_TASK_ID)
